### PR TITLE
plugin "autozoom" using webapi and web plugin interface

### PR DESCRIPTION
**Pull request by u-an-i**
@albar965 I couldn't test it wrt the zoom behavior because my build doesn't connect to FS2020. I downloaded and installed the FS2020 SDK and set the SimConnect Path but I got an error about "simconnect.h" not found.
Do I have to copy that file somewhere? The webapi delivers `"active" = false` when there is no connection to the simulator, thus i couldn' test the core purpose of the plugin.

@KOKAProduktion the value delivered for `zoom_web` is in the 2000 range while the value sent to `requesthandler.cpp` is around 8. See the maprequest handling concerning (real) zoom distance. This is the value I would like.

### CODE REVIEW

**Comment by KOKAProduktion** [comment]
> the value delivered for zoom_web is in the 2000 range while the value sent to requesthandler.cpp is around 8. See the maprequest handling concerning (real) zoom distance. This is the value I would like.

The fix for this is at #776 

Cheers!

**Comment by u-an-i** [comment]
I am using the distance value delivered by @KOKAProduktion latest PRs code now.

@KOKAProduktion Do you mind reviewing this PR ?

Both of you and the author of https://github.com/albar965/littlenavmap/issues/526#issuecomment-917537488 might like that the values the plugin is based on are defined in a seperate, documented file for easy user modification.

I tested the current values with an FS2020 Icon A5 and a Typhoon Eurofighter.

**Comment by u-an-i** [comment]
demo ("long"):

https://www.youtube.com/watch?v=MdU58G23XiY


@albar965 i thought a smooth zoom might look great and contemplated looking into marble to "fix" the current issue. (but not until late wednesday evening). Do you think this is worthwile and time well spent now?

**Comment by KOKAProduktion** [comment]
Cool @u-an-i! 

Yes, I will check this out! But please give me some time.

Thx and cheers!

**Comment by albar965** [comment]
> i thought a smooth zoom might look great and contemplated looking into marble to "fix" the current issue. (but not until late wednesday evening). Do you think this is worthwile and time well spent now?

Sorry, the video is a bit too long to search through. Can you give me a timestamp?
What needs to be changed in Marble?

I'm stuck with an older Marble version, BTW. This is because I'm afraid of side effects when updating and I already noticed that newer Marble versions still have the same old bugs.

**Comment by u-an-i** [comment]
> Sorry, the video is a bit too long to search through. Can you give me a timestamp?

takeoff https://youtu.be/gSQibrzjlew?t=1340

intermediate https://youtu.be/gSQibrzjlew?t=9789

approach https://youtu.be/gSQibrzjlew?t=10355

(different video, more to see)




> What needs to be changed in Marble?

nothing yet, i only hit dead ends i considered reporting about but then left it for the time being. I have a hunch it is due to rounding. Marbele keeps zoom and diatnce separately which are related by a power of 2 but round sone into an int. If the round up instead of down or vice versa within a "zoom range", they might end up with a map at a certain zoom level but paintings (text etc) being the size of a different zoom level.
I basically failed at finding where Marble triggers its drawinf and does the drawing.

**Comment by albar965** [comment]
Thanks. The zooming looks almost like the default LNM zoom.
If you mean soft transitions between zoom: Marble can already do this but I disabled it everywhere to avoid stutters (not so smooth as a result). Disabled here:
https://github.com/albar965/littlenavmap/blob/245c28adad22539f3b559757791c4d9c946d61de/src/mapgui/mappaintwidget.cpp#L72-L75

You're aware that LNM zooms one step out to get a sharp map? The map can turn very fuzzy if you omit this step. Marble somehow manages to get the worst image resolution at times. Try Shift+Wheel to see the fuzzyness.
No idea where the zoom vs. distance thing can be fixed in Marble. These guys have some very heuristic approaches in there.

**Comment by u-an-i** [comment]
> You're aware that LNM zooms one step out to get a sharp map?

yes

> Marble can already do this

ah! But for the web ui each smooth step would actually have to be requested which would not appear smooth likely except if i buffer ~ 10 interemdiate steps and then run them which would delay the zoom (perhaps negligibly). Perhaps not worth further effort.

**Comment by albar965** [comment]
> ah! But for the web ui each smooth step would actually have to be requested which would not appear smooth likely except if i buffer ~ 10 interemdiate steps and then run them which would delay the zoom (perhaps negligibly). Perhaps not worth further effort.

Right. I forgot about the web aspect and data transfer. Stupid me. :upside_down_face: 
And yes, too much effort.

**Comment by KOKAProduktion** [comment]
Hi @u-an-i,

Sry for the silence. I'll review this on Monday too.

Cheers!

**Comment by KOKAProduktion** [comment]
Still at it :)

**Comment by KOKAProduktion** [comment]
Hi @u-an-i,

tested this PR with FS2020 and Firefox. Works like a charm! Really cool plugin! I think it has great potential for becoming default behaviour.

Approving this PR.

Thanks and good night! Damn i didn't make it until Wednesday... Sorry!

**Comment by u-an-i** [comment]
Hi, @albar965 this PR can be merged at your convenience.

**Pull request merged**
