### PR TITLE
add mousewheel zoom and pinch gesture zoom

### PR DESCRIPTION
**Pull request by u-an-i**
as well as accompanying mobile optimisation

Note: I reduce the jpg quality during zoom for a smooth experience. The common code could be merged with reloadMap but currently i have no good idea to have such a function not be overblown with features and thus perform "slower" for specific tasks than the current way where performance is rather crucial in theory.

### CODE REVIEW

**Comment by u-an-i** [comment]
thinking about this, the interaction type for "click" could now be omitted and click would always shift. What do you think?

**Comment by u-an-i** [comment]
Because a rectangle is already supported as a map command, zooming into the location where the mouse cursor points to would only require me to now the values of the initial rectangle. On the other hand I like the stability of zooming into the fixed center.
Also, the rectangle and the image dimesions might have different widths / height, the rectangle command would only need 1 side, eg width and determine the other side from the image apsect ratio itself.

**Comment by u-an-i** [comment]
I added a commit making the map update code more concise and deleted the interaction options (i apologize for not waiting, ignore this commit at your discretion) and changed the refresh dropdown to a refresh slider (121 values along 121px).

**Comment by u-an-i** [comment]
if you don't like the slider, which I just gave a little bit more width, I replace it by your dropdown placeholder again.

See images from iPad and iPhone below (note the map button bar can be scrolled on iPhone):

image
image
(the colors are the example theme (in case you haven't tried it yet))

**Comment by albar965** [comment]
> thinking about this, the interaction type for "click" could now be omitted and click would always shift. What do you think?
I'd keep it if not too much effort to maintain both. People like choices. :slightly_smiling_face: LNM also has different zoom and scrolling modes one can change in the options.

> if you don't like the slider, which I just gave a little bit more width, I replace it by your dropdown placeholder again.

Slider is perfect. Better than the dropdown box.

**Pull request merged**
