### PR TITLE
add map refresh options as described

### PR DESCRIPTION
**Pull request by u-an-i**
center aircraft,
zoom level,
retina map image variant,
ui streamlining like warnings, indicators, presentation order,
minor code clarity improvements

### CODE REVIEW

**Comment by u-an-i** [comment]
I noticed the map image dimensions relayed to the server are taken into consideration for the "field of view" (ie larger image width = broader longitudinal section).
My expectation was the "field of view" is determined by a "current zoom level": the zoom level dictates the lateral/longitudinal section (or cone / sphere intersection radius) and the mapped geography inside is rastered onto the image dimension, and if for example longitudes from 10 to 30 are put on a 300px wide image the mapped geography is less resolved than when the image is 700px wide.

Can you adjust the map image generation? If not, removing the "Retina map image" option should be done because it doesn't add anything as far as I currently see (except data size ;( :) )

**Comment by u-an-i** [comment]
If you don't mind, wait with evaluating this PR. I'm thinking of having the sliders vertically, opened by toggle. This would be 1 extra click, but saves bar estate on iPad. Perhaps I also do this for such small screen devices only. I found out, now the "prevent standby" checkbox moved out of the view port on iPad due to the zoom slider (which accompanies aircraft autocenter) (I thought it a good idea to offer a configurable zoom here; before it was always 50% between min and max) and one has to scroll the bar on iPad to get to it. Athough scrolling is an intended feature and helpful the more items on the bar, in my tests today on iPad with several reloads I would have preferred this checkbox be instantly visible there (default iPad screen timeout is 2 minutes and being able to prevent standby always is somewhat crucial (it cannot be default because it is solved as a video with audio playing and having a video with audio autoplay is suspended by iPad OS)).

**Comment by albar965** [comment]
No prob. Take your time. Working on other issues for now and will get back to you.
Will also have a look at the fov issue. Not sure if I can change this since it is handled by the Marble library.

**Comment by u-an-i** [comment]
Thank you for your understanding! I'm glad to read this!

I had an idea about an "auto zoom": zooming into the map for crucial navigation and adjusting the refresh rate for smooth updates automatically. I implemented an experiment in JS in the web ui. Here's a video of it in action: https://1drv.ms/v/s!Ag8I6whv8uZOzcUddNKi9jLOFm3L0g?e=1aNhyX  (4x speed). By chance you offer this already? Or would it be something you would like to offer on the server? Find the experiment in branch https://github.com/u-an-i/littlenavmap/tree/feature/auto-zoom-and-auto-refresh.

Is there something you would like to have tackled on the web side or need help else? I'm open to help.

Other than above, I would look into the first request of #581 .

**Comment by u-an-i** [comment]
Hello :),

looked at Marble: their zoom is an "integer without physical representation".

I try to handle this on the web frontend side: by experimenting with 2 different image dimensions, i can try to see which 2 zoom values are required to make them look equal regarding the geo fov. Hoping the relation is linear i can then handle this from JS.

I would need to extend the server: you offer zoom as "distance" for some commands already but not all.

Can you give me some pointers where I can find:

- the server commands handling
- the distance parameter interpretation (it only takes certain integers, not all and not decimal preventing smooth zooming from the web)
- the quality parameter interpretation (i noticed > 30 (type jpg) does not make a difference I was aware (in image applications I have come across jpg compression quality ranging from 0 to 100 in where 30 to 70 had discernible differences for me))
- the Marble MapQuality setting which appears to offer only 4 meaningful values and which not appears to be exposed yet.

if you have leisure.

**Comment by albar965** [comment]
Distance corresponds roughly to view distance above earth surface:
http://localhost:8965/mapimage?format=jpg&quality=100&width=768&height=768&lon=-4.99528&lat=50.4408&distance=1

Where the distance parameter is set using this method (converted from NM to km):
https://github.com/albar965/marble/blob/master/src/lib/marble/MarbleWidget.h#L653-L657
LNM might zoom one step out after setting distance to avoid a fuzzy map background.

HTTP server code is here:
https://github.com/albar965/atools/tree/master/src/httpserver
Cloned from this one: http://stefanfrings.de/qtwebapp/index.html

LNM specific handler code is here:
https://github.com/albar965/littlenavmap/tree/master/src/web
Request handler:
https://github.com/albar965/littlenavmap/blob/master/src/web/requesthandler.h

Hope this helps.

About auto zoom: The video is cool. I think most people are dreaming of these update rates like 0.4 seconds. 
But I'm a bit confused. Is this default LNM zoom behavior or do you build something else?

Some issues with the web server in general: 
- The MapWidget takes over almost all settings from the GUI map display. It is not completely independent. Would be cool if one could change the map display settings in the web UI (lets keep this for future updates).
- The whole thing does not scale. Do not expect to run this on a server with high load. There is only one MarbleWidget which can deliver images and this cannot deal with threads.

**Comment by albar965** [comment]
BTW: Another web-stuff related issue: #397

**Comment by u-an-i** [comment]
Thank you very much!

The update rate 0.4 is theoretical (what would be needed for smooth aircraft animation in the autozoom branch under the flight conditions then) (Mach 2 Eurofighter) but LNM didn' react that fast;
I wait for the last request to complete before i send a new request, otherwise one might never receive a result (at least for me, triggering without waiting caused a cancellation of the previous request in Chromium-Edge).
This is part of the new ui for map.
I used the same server from an iPad (internet, which is the screen record), and the desktop on localhost.

It is default LNM zoom behaviour, I discovered the "distance" set to static "5" with some commands in the original JS. In the autozoom branch I wrote JS code to adjust this value sent to the server.

#397 is exactly what I can ideally need for "autozoom" :) Currently, I extract the flight parameters from "parsing" the progress.html.
I'll see what I can find with the server code!

**Comment by albar965** [comment]
Yeh. What you see is the limitations. Only one Marble widget instance to generate the images. I'm not really keen to keep a pool of these things. :slightly_smiling_face: 

Generating the progress HTML (same as in LNM tab) is a bit painful. There are so many conditions in there that I'm hesitant to change the code to produce JSON.

**Comment by albar965** [comment]
A related PR, BTW: #622

**Comment by u-an-i** [comment]
#622 reads very brilliantly! I don't know OpenLayers. I take a look at it.

Before building LNM, I need  to configure it inside the Linux VM I set up because the troubles you mentioned with Windows in the Wiki here let me not want to risk my brisk Windows main machine. Looking forward to get it running over the holidays the next 2 days.

**Comment by albar965** [comment]
I'd like to make a release in the next week (or so). Is there any stable (maybe intermediate) state I can use for this?
Would be cool if we could already offer the changes to the users.

**Comment by u-an-i** [comment]
I think so.

Summary of my thoughts:

- i'm unhappy with the refresh slider ui: i don't need most of the values possible and even though i can adjust it to each of the 121 values offered even on iPad , that turned out to be tedious over time
  - alternative is a slider decoupled from the header button bar (as popup) with more space given to it;
  I experimented with this (horizontal and vertical slider) but i didn't like it either: i either have to move the mouse over a much longer distance or move my eyes even on iPad over a longer distance to follow my manipulation of the slider which felt uncomfortable.
  - i thus had the idea to simply offer a checkbox "auto-refresh": update instantly after the last update returned.
  This is the shortest possible refresh now already: even if 1s is chosen, if server and network don't keep up, a new request is only made when the last returned. I added this "invisible" in this or the last PR (only for the new ui!).
    - this would still possibly make the server and network more busy than liked (ie the resources could be better used for the sim)
      - solution 1: an advanced option with a text field where the user can enter his own delay of any size -- most functional and the smallest ui occupancy solution of anything which requires ui (dropdown, slider)
      - solution 2: a checkbox "auto-delay" like I already implemented for the "autozoom" inside the other branch I didn't create a PR for yet because it requires server work (see a comment you replied to above) for general (and 100% safe) application (data as JSON instead of parsing HTML -- by the way: keep the old code! just add json separately if you attempt this)
      - solution 3: speech recognition could be cool.
      speech synthesis is as simple as coding "browser.setVoice("Mary");browser.speak("word")" (api names actually different);
      I implemented such for other projects. If i remember correctly I glanced from the documentation back then that speech recognition is equally simple. Then we could offer recognition for "map -- zoom, map -- widen, map -- follow, map -- aircraft, map -- refresh, map -- set 10 refresh".
- the "prevent standby" option moved out of the initial view of the button bar. I don't like this on iPad.
  - this would be rectified by any solution to the refresh slider above other than leaving it as it currently is.
- Retina map image done right.
high dpi devices don't tell the physical pixel size to CSS and JS by default. Thus on a phone, the map would be gotten as 320px wide although it could be 1080px wide. The current option "Retina" does this. But the zoom is different, see that comment about zoom above.
  - I need to get the app build running to be able to update the server code for to adjust the zoom smoothly from web frontend and support zoom for every map command.
    - if i don't achieve this by tomorrow evening, I hide the retina checkbox for now (it already is hidden on "standard dpi" devices (check yourself by switching Windows desktop dpi ("100%", "125%", "150%", ...; 100% = standard))).
- other than these, everything works and is free of known issues.
- i like to look at #622 and #581 suggestions but at least #622 might take time getting to know the "OpenLayer" software (it sounds like a framework which requires a own, particular coding style). Perhaps both of them are better suited to a separate PR anyway.

**Comment by albar965** [comment]
> - i'm unhappy with the refresh slider ui: i don't need most of the values possible and even though i can adjust it to each of the 121 values offered even on iPad , that turned out to be tedious over time
>   - alternative is a slider decoupled from the header button bar (as popup) with more space given to it;
>   I experimented with this (horizontal and vertical slider) but i didn't like it either: i either have to move the mouse over a much longer distance or move my eyes even on iPad over a longer distance to follow my manipulation of the slider which felt uncomfortable.
>   - i thus had the idea to simply offer a checkbox "auto-refresh": update instantly after the last update returned.
>   This is the shortest possible refresh now already: even if 1s is chosen, if server and network don't keep up, a new request is only made when the last returned. I added this "invisible" in this or the last PR (only for the new ui!).
>     - this would still possibly make the server and network more busy than liked (ie the resources could be better used for the sim)

Best solution for now IMO. Update after last reply but not more often than one or two (?) seconds. Some reasonable value to avoid draining the battery. Add the choice later.

> - solution 1: an advanced option with a text field where the user can enter his own delay of any size -- most functional and the smallest ui occupancy solution of anything which requires ui (dropdown, slider)

Even better than above solution with fixed timeout.

> - solution 2: a checkbox "auto-delay" like I already implemented for the "autozoom" inside the other branch I didn't create a PR for yet because it requires server work (see a comment you replied to above) for general (and 100% safe) application (data as JSON instead of parsing HTML -- by the way: keep the old code! just add json separately if you attempt this)
>       - solution 3: speech recognition could be cool.
>       speech synthesis is as simple as coding "browser.setVoice("Mary");browser.speak("word")" (api names actually different);
>       I implemented such for other projects. If i remember correctly I glanced from the documentation back then that speech recognition is equally simple. Then we could offer recognition for "map -- zoom, map -- widen, map -- follow, map -- aircraft, map -- refresh, map -- set 10 refresh".

This would be really cool. But I think this should be considered for future LNM updates (maybe 2.8).

> - the "prevent standby" option moved out of the initial view of the button bar. I don't like this on iPad.

Maybe omit this since people can use other solutions like Caffeine on Android.

>   - this would be rectified by any solution to the refresh slider above other than leaving it as it currently is.
> - Retina map image done right.
> high dpi devices don't tell the physical pixel size to CSS and JS by default. Thus on a phone, the map would be gotten as 320px wide although it could be 1080px wide. The current option "Retina" does this. But the zoom is different, see that comment about zoom above.
>   - I need to get the app build running to be able to update the server code for to adjust the zoom smoothly from web frontend and support zoom for every map command.

Later for 2.8. I'd rather concentrate on what there is right now for the update.

> - if i don't achieve this by tomorrow evening, I hide the retina checkbox for now (it already is hidden on "standard dpi" devices (check yourself by switching Windows desktop dpi ("100%", "125%", "150%", ...; 100% = standard))).
> - other than these, everything works and is free of known issues.

Okay. I'll merge all you PRs into the branch `release/2.6` and have a look at it. 
The changes and improvements are already outstanding and I'm sure people will freak out about them.

> - i like to look at #622 and #581 suggestions but at least #622 might take time getting to know the "OpenLayer" software (it sounds like a framework which requires a own, particular coding style). Perhaps both of them are better suited to a separate PR anyway.

Maybe contact @KOKAProduktion about #622 to combine the efforts.

Alex

**Comment by albar965** [comment]
Merged all to `release/2.6`. This can go into 2.6.12.
Looking good!

**Comment by u-an-i** [comment]
Hi, thanks and thank you!

I'm currently just transforming the refresh slider to a refresh checkbox with input. I guess i push in about 1 h.

**Comment by u-an-i** [comment]
(new branch)

**Comment by albar965** [comment]
No prob. Still testing the beta internally.

**Comment by u-an-i** [comment]
have been working on this: I need some more hours, later (also discovered one or 2 issues i fixed).

**Comment by u-an-i** [comment]
https://github.com/albar965/littlenavmap/pull/658

**Comment by KOKAProduktion** [comment]
Good morning guys! 

@albar965, thx for tagging me.
@u-an-i, wow, this looks pretty cool! I can't wait to try it out in action! Thank you! 

Please give me a few days to get myself back on track here and I will add my thoughts on possible options.

As for OpenLayers I'm still convinced it's a good idea and my guess is, @u-an-i that you'll probably love it once you get into it. I'm still hyped to contribute, either as a coder of some parts or just a supporter. But as said, let me get my thoughts together on the current state first and get back to you.

Have a nice weekend and hear you soon!

**Comment by u-an-i** [comment]
Hi @KOKAProduktion ,

I looked at OpenLayers and your code. Look easy-breezy in fact! :)

ingenious finding of yours to use the Rectangle command as a "tile server"!

Sure, time's ample (for me (i think/feel/think i feel)) !

My question is whether i like the UX/UI once i see it in action. :)
 i considered smooth (elastic) panning, layered smooth icons and zoom where you point first too but then imagined it and think now i prefer a/the look and feel of conveying stability. (but just might be my drooling in the thought of what (i) just "created" and fearing loosing comfortable feeling)

Alex wrote "people like options" so if you/we can accomodate it, it will be i guess :) Feel free to create a PR i guess :)
or if Alex prefers it, it will become the default, he decides after all.

enjoy

being enthusiastic

**Comment by albar965** [comment]
I opened Github discussions for LNM here:
https://github.com/albar965/littlenavmap/discussions
I think this is a good place to talk about technical stuff.

**Comment by albar965** [comment]
> Alex wrote "people like options" so if you/we can accomodate it, it will be i guess :) Feel free to also just create a PR i guess :)
> or if Alex prefers it, it will become the default, he decides after all.

That's still true but I also learned that too many options can increase testing and maintenance a lot. I leave this for you to fight out. :smile:

**Comment by KOKAProduktion** [comment]
> That's still true but I also learned that too many options can increase testing and maintenance a lot. I leave this for you to fight out. 😄

Hahaha! Smart move!

Hear you soon :D

**Comment by KOKAProduktion** [comment]
Collected my thoughts at #677

**Pull request merged**
