### PR TITLE
Add pipeline script for Travis CI

### PR DESCRIPTION
**Pull request by prinz7**
This pull request contains a pipeline script for the Travis CI regarding to the first part of issue #154 .

I set up the build process in a way so that I dont have to change any of your files. That means for example, that the custom marble is installed at "/home/alex/Programme/Marble-release" because of the hardcoded paths in "littlenavmap.pro".

You can see the build results of the forked project at [https://travis-ci.com/prinz7/littlenavmap](https://travis-ci.com/prinz7/littlenavmap).

I would recommend you to activate your project on [https://travis-ci.com](https://travis-ci.com) before merging this pull request (not travis-ci.org which seems to be the legacy version), so that the merge commit is built straight away.
After that every commit (and pull request) on a branch, containing this script, should be built automatically.

So far the pipeline definition only contains a build for linux. I think other operating systems should be possible too, even though Windows could be more difficult. I can look at that later if you want.
But I guess the other parts of the issue with the coverity scan and the automatic deployment are more important. Especially the deployment would be helpful. That should be done in your subprojects too, beacause the build takes relatively long with about 30 minutes. But building littlenavmap itself only takes 6 minutes. So marble and atools should deploy their artifacts automatically and littlenavmap should only use them. But I would like to hear your opinion on that first

### CODE REVIEW

**Comment by albar965** [comment]
Thanks, Jannik. Very, very helpful!

A few remarks:

- I have no clue about Travis CI. Only worked with Jenkins so far.
- I'll make the LNM and atools builds more configurable using environment variables to avoid these hardcoded paths. I promise. :)
- For running tests on the atools library is a separate repo which uses the Qt test framework: [atoolstest](https://github.com/albar965/atoolstest). This does not cover all from atools by far but is maintained.
- Besides the atoolstest I'd like to run automated tests on LNM itself which should be GUI based. Qt test framework allows to inject GUI events into the application.

Alex

**Comment by albar965** [comment]
More: Builds would be needed for Windows and macOS. I guess the latter one is hardly doable.

I build the releases using a [bunch of scripts](https://github.com/albar965/littlenavmap/tree/master/build) which are mostly hardcoded for my purposes to create the programs in VMs.
Automatic deployment would be terrific.

**Comment by prinz7** [comment]
I am new to Travis CI too, but it seems quite comfortable. Just adding the script on the project and activating travis on the account and everything else works automatically. No further setting is needed.

I was already wondering if this project has no tests. The tests for atools should be executed in the pipeline of the corresponding project. I would set up the CI there too. This is connected with the proposal I wrote in the description. I dont think the build of littlenavmap should directly depend on the build of marble or atools.

So I would propose the following next steps:
1. Establish a CI for atools (including the corresponding tests)
2. Test how the automatic deployment of the build artefacts work
3. Test how these artefacts can be fetched in this pipeline
4. Do the same with marble  
5. Steps after that (unordered):  
  - Establish automatic deployment of littlenavmap itself. Here we should think about how we separate release builds from the rest (if a deployment is wanted for non release builds in the first place) 
  - Adapt pipeline to build for mac and windows (with parallel jobs) 
  - Add a test stage for this pipeline (when tests are added)

What do you think?

Jannik

**Comment by albar965** [comment]
Sorry, gimme a day or two. I'm currently taking the build and pro-files apart for a more configurable deployment.
Alex

**Comment by albar965** [comment]
Hi Jannik,

Took a while longer to get the build fixed and to test it on all platforms. Bug me per email if you have time and I take too much time to answer. 

The build instructions are now updated. You can now put all dependents in one folder using default names or you can override all paths with environment variables.

atoolstest is not yet adapted. Will do that the next few days.

> Establish a CI for atools (including the corresponding tests)

Absolutely needed. I'd propose this as the next step.

> Test how the automatic deployment of the build artefacts work

Can be difficult for Windows and macOS. I'd say: Do this for Linux first and then have a look at Windows.

Getting the Windows and macOS deployment fixed on Marble would be helpful but I have no clue about cmake. Let me know if you could have a look at this.

> Establish automatic deployment of littlenavmap itself. Here we should think about how we separate release builds from the rest (if a deployment is wanted for non release builds in the first place)
Let's get started with nightly builds for Linux and then check out the Windows issue.
I'd put macOS on lower priority.

Send me an email (German or English) if you like to put this discussion offline.

Best,
Alex

**Pull request merged**
