### PR TITLE
added plugin type "widget", added documentation accordingly, reformat…

### PR DESCRIPTION
**Pull request by u-an-i**
…ted and rephrased toolbar API documentation, added example plugin for widget, enhanced example plugin for exclusive plugin to demo attribute overriding, minor ui update to ol-map plugin, let map zoom be default quality initially, afterwards subsequent continued zoom then uses fast map quality, minor ui update re checkbox positioning, automated and auto-safeguarded plugin type transfer, don't reinit map or addon iframe when same content already present

### CODE REVIEW

**Comment by u-an-i** [comment]
@albar965 i was in a desire to implement a streak of ideas.

**Comment by albar965** [comment]
> i was in a desire to implement a streak of ideas.

I fully with you but we've gotta be cautious not to break plugins using the API like https://flightsim.to/file/43086/little-navmap-vr-panel and https://flightsim.to/file/43086/little-navmap-vr-panel .

Alex

**Comment by albar965** [comment]
Nice. Like the floating ICAO field in the OL map. :slightly_smiling_face:

**Comment by u-an-i** [comment]
> I fully with you but we've gotta be cautious not to break plugins using the API like https://flightsim.to/file/43086/little-navmap-vr-panel and https://flightsim.to/file/43086/little-navmap-vr-panel .
> 
> Alex

Sure! I wasn't aware other web plugins exist. Those 2 are the same link. They appear to be using the **wep api**. That is not changed ! The **web plugin api** _did change_ with the previous PR regarding initialisation:

`function init (message) { var returned_Value = message.pluginParent.callback(message.pluginParent.callback.TYPE_XXX, stop_Method); ...` instead of `function init (callback, version) { var returned_Value = callback(callback.TYPE_XXX, stop_Method); ...`.

This was done to make possible future migration to a different communication technology more straightforward if iframe security changes occur.

**Comment by albar965** [comment]
Copy and paste error:
https://flightsim.to/file/43086/little-navmap-vr-panel
https://flightsimulator.me/simulators/flight-simulator/panels/105-ingamepanel-navmap-for-flight-simulator

Alex

**Pull request merged**
