### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by J0hnLiu**
Based on release/2.4

### CODE REVIEW

**Comment by tonghuix** [comment]
@J0hnLiu  Some of your translation are not meed the critira of The Chinese Translation Guidence for Free Software https://mirror.koddos.net/anthon/aosc-l10n/zh_CN_l10n_1.2.0.pdf

Could you please update it? And for the aviation terminology please refer ICAO DOC 9713.

**Comment by J0hnLiu** [comment]
@tonghuix  Sure, will do.

**Comment by albar965** [comment]
I just published a [release candidate rc1](https://www.avsim.com/forums/topic/573892-little-navmap-245-release-candidate-for-p3d-v5/). You can use this to test the  translations.
Alex

**Comment by albar965** [comment]
Let me know how it's going. I'd like to publish the release on Sunday if possible.
Alex

**Comment by J0hnLiu** [comment]
I'm still working on double checking, will try my best to have it done today.

**Comment by J0hnLiu** [comment]
I'm marking this pull request for review for release/2.4.5, however there are some unfinished blocks due to my limited aviation English, please feel free to [contribute to this translation](https://github.com/J0hnLiu/littlenavmap) or [File a issue](https://github.com/J0hnLiu/littlenavmap_translation_zh/issues/new).
Most of unfinish blocks are in QObject starting from Custom Fix.

**Comment by albar965** [comment]
Will merge tomorrow morning (around 12:00 UTC). Feel free to add any updates until then.
Alex

**Pull request merged**
