### PR TITLE
Completed Chinese translation for littlenavmap

### PR DESCRIPTION
**Pull request by J0hnLiu**
Forked from master version.

### CODE REVIEW

**Comment by tonghuix** [comment]
牛逼！

**Comment by J0hnLiu** [comment]
@tonghuix Join me and refine the translation if you wish. 如您愿意可以加入一起完善这些翻译，现在他们还很初级，存在不少错误。

**Comment by tonghuix** [comment]
I am reviewing this translation, some entries are need correct for standard aviation terminology.

**Comment by J0hnLiu** [comment]
Great, let me know your finding.

**Comment by albar965** [comment]
Merging. Will update translation files once in branch `release/2.4` and send them to you.

**Pull request merged**
