### PR TITLE
Merge pull request #1 from albar965/master

### PR DESCRIPTION
**Pull request by efa**
Synch with 2.0.1b

### CODE REVIEW

**Comment by albar965** [comment]
Maybe I'm too stupid to use this web interface but I cannot find out what has changed?
Or should I just merge the release/2.0 back to master?
Alex

**Comment by efa** [comment]
On 07/05/2018 23:44, Alexander Barthel wrote:
> Maybe I'm too stupid to use this web interface but I cannot find out 
> what has changed?
> Or should I just merge the release/2.0 back to master?

I think you can ignore, probably I had done some mistake pulling YOUR 
updates to my OLD fork. Then I had cloned the github to my local copy.

I'm just now translating some new strings in 2.0.1b

Valerio

**Comment by albar965** [comment]
Latest is on release/2.0. I did not touch the WIP translation files to avoid conflicts. I was also a bit too lazy merging into feature/translation.

I can also pull an incomplete translation file into the release if you don't mind. 

Let me know what you think.
Alex

**Comment by efa** [comment]
On 08/05/2018 00:02, Alexander Barthel wrote:
> Latest is on release/2.0. I did not touch the WIP translation files to 
> avoid conflicts. I was also a bit too lazy merging into feature/translation.
> 
> I can also pull an incomplete translation file into the release if you 
> don't mind.
> 
> Let me know what you think.

I synched branch master, feature/translation and release/2.0
I'm still working on "feature/translation" branch.
Today I updated the littlenavmap_it.ts file, fixing all changed strings 
respect 1.x and adding some other.

Situation is 644/2829 translated strings, also on github.

Did you ear the other IT translator Cele91?
https://github.com/albar965/littlenavmap/issues/135

Valerio

**Comment by albar965** [comment]
Sorry for being a bit stupid. Should I merge the pull request now? 
Looking at the diff I'd rather not like to.

**Comment by efa** [comment]
merging can be an easy start point if another IT translator want to contribute. As now we can continue as so, github work as backup of my local files, we will merge the final work.

**Comment by albar965** [comment]
OK. Fine with me.

**Comment by albar965** [comment]
Hi Valerio,
can I close this? I see no apparent changes.
Alex

**Comment by efa** [comment]
yes

**Pull request closed without merging**
