### PR TITLE
quick creation of random flight plan

### PR DESCRIPTION
**Pull request by u-an-i**
for finding new adventures.

Unfortunately it doesn't have departure and destination added to the flight plan and I don't know where I can see the status messages.

### CODE REVIEW

**Comment by albar965** [comment]
Related to #88.

I'd rather have the user select all kind of criteria in the airport search (min runway length, ILS, procedures, country and whatnot) and then generate a random plan (allow to select min and max traveling time before) from this result set. This would allow a lot of options with functionality already present.

**Comment by KOKAProduktion** [comment]
Oh, very cool feature! Nice!

**Comment by u-an-i** [comment]
ah, the Search window, I hadn't used it yet and didn't think of looking into the Window menu entry and already wondered where an airport search could be given one is available from the web interface :)

Yes, I already thought of having a dedicated (Generator) window with settable parameters for random creation (one wouldn't want to takeoff an airliner from a grass airfield) but then I didn't know how to query for such restrictions without random searches which might take a long time until an appropriate match is found.

I'll look into the code behind the Search window to see what I can do. A "create random plan" button might just fit into the Airport Search tab :)

**Comment by albar965** [comment]
I added more information and a proposal how to do this in the search window in #88. 
Hope this helps. Lemme know what you think about this.

**Comment by u-an-i** [comment]
next to the "full solution" https://github.com/albar965/littlenavmap/pull/773 i leave this PR with a rename as "quick random flight plan"

**Pull request closed without merging**
