### PR TITLE
fix JS errors on Desktop due to pointermove after generalising touch …

### PR DESCRIPTION
**Pull request by u-an-i**
…zoom, handle case if server does not respond, give user commands always priority, adjust fastRefreshMapThreshold to not produce images too large at current fastRefreshMapQuality on "slow 3G" (as given by Chrome developer tools) for new handling of a possibly not responding server

### CODE REVIEW

**Comment by u-an-i** [comment]
@albar965 with the last PR I generalised the Android touch zoom solution to also be used on iOS. Apparently I didn't check the Desktop developer console because that generalisation produces JS errors (which don't break the page) when moving the mouse across the map, I fixed this in this PR.
The way map image updates work the new web UI used a "lock" to only request a new image when the previous requested image arrived as to not have previous requests getting cancelled by new requests and thus the user being without a map image at all, eg. on low auto refresh interval values with a slow connection (when used across the web). I now added code to remove that lock after 10 seconds (which is the just above the time a map image inside a maximised FullHD Desktop browser window takes to load on "slow 3G" connection (according to Chrome developer tools)) so that eg in case of server failure for a particular command other commands can get requested.
Also user commands like zoom now always pass through a lock, so that for example when an auto refresh of 1s locks other requests when waiting for a refreshed map, the user command is obeyed (instead of being discarded which would lead to a seemingly unresponsive page).
I expanded the documentation for these parts.

**Comment by albar965** [comment]
Just built and uploading 2.6.15. Is this serious issues? Happens often?

**Comment by u-an-i** [comment]
> ~Just built and uploading 2.6.15. Is this serious issues? Happens often?~
> 
> Edit: Disregard. Just set the tags. I'll implent this for 2.8 or a 2.6.16.

The JS errors always occur on Desktop, they are due to mouse movement also being a pointer movement which are checked for pinch zoom but mouse movement doesn't have the required prerequisite thus the code checking pointer movement throws an error and "does nothing" on Desktop which is not breaking anything. The remainder "only" is handling a case which didn't occur yet but I noticed I could not rule out.

Did you mean I should set tags? If so, how? :)

**Comment by albar965** [comment]
Good if it does not break anything. :slightly_smiling_face:  I quickly tried the web interface before releasing and saw no apparent issues.

> Did you mean I should set tags? If so, how? :)

Never mind. I already had the tags set when your PR came in. Sorry, was not clear.

I already had the full version and all builds ready when I discovered a crash when moving flight plan legs under certain circumstances. Therefore, I was not really keen to start the whole process over again.

I'll leave a sort of pre-release notification a few days before in the forum next time.

Alex

**Comment by albar965** [comment]
I'll add this to a potential 2.6.16. 

**Thanks for the contributions, BTW!**

**Pull request merged**
