### PR TITLE
add client-given distance support for all remaining commands other tha…

### PR DESCRIPTION
**Pull request by u-an-i**
…n zoom in and out

Note: I did not test this! I haven't built LNM with Qt 5 yet. Perhaps @KOKAProduktion can help?

### CODE REVIEW

**Comment by u-an-i** [comment]
see https://github.com/albar965/littlenavmap/pull/686/commits/564a6e08bc3578206e7614045b98969b9f4079a7 for taking into consideration user zoomed in and out. Added there because there code structure changed creating places where that code needs to be placed.

**Comment by albar965** [comment]
Will check.

**Comment by albar965** [comment]
Zooming is broken now. Moving will zoom out one step for each move.

**Comment by u-an-i** [comment]
i found 1 issue in the JS after moving the "set zoom level" to a server command which stores the zoom level inside the session.

i will create a PR for this

Afterwards additionally i look explicitly into the move / zoom logic.

**Comment by u-an-i** [comment]
PR https://github.com/albar965/littlenavmap/pull/690 to fix JS.

Note: merge https://github.com/albar965/littlenavmap/pull/689 first. In the merge conflict when merging above PR 690, take the code from 689 and delete the "&" in front of "reload" (on line 221 i guess).

i found an issue related to zoom on server, fixed in PR https://github.com/albar965/littlenavmap/pull/691.

If above PR 691 does not fix the "moving zooms out", i have to understand the zoom application better: for moving zoom used to take the session value "requested_distance" -- logically following a user zoomed in or out. I changed this to user submitted zoom (so that the new web ui zoom slider takes effect). Once I realised this ignores the zoom in/out in commands after, I fundamentally store the zoom on the server and use it if not explicitly overridden by web ui (as from legacy ui), the new web ui now does not submit a zoom to commands, it only updates the zoom sesssion on the server. So for moving, the zoom now again uses session "requested_distance" (by the default parameter passed to params.asFloat("distance")). If the user zooms by wheel or pinch, I have to fetch the new zoom value from the server occurs to me just now to reflect it in the new web ui zoom slider. I add this after the issue here is solved.

**Comment by u-an-i** [comment]
(as all commands now obey the same zoom level - the zoom level from the session - and mouse wheel and pinch set the session value - i just thought we can delete the zoom slider from the new ui (thus not needing the new path and not needing to update the slider from one))

**Comment by KOKAProduktion** [comment]
Same here: I can only test the Win10 build and only when provided some test instructions :)

Thx & Cheers

**Comment by albar965** [comment]
> PR #690 to fix JS.
> 
> Note: merge #689 first. In the merge conflict when merging above PR 690, take the code from 689 and delete the "&" in front of "reload" (on line 221 i guess).
> 
> i found an issue related to zoom on server, fixed in PR #691.
> 
> If above PR 691 does not fix the "moving zooms out", i have to understand the zoom application better: for moving zoom used to take the session value "requested_distance" -- logically following a user zoomed in or out. I changed this to user submitted zoom (so that the new web ui zoom slider takes effect). Once I realised this ignores the zoom in/out in commands after, I fundamentally store the zoom on the server and use it if not explicitly overridden by web ui (as from legacy ui), the new web ui now does not submit a zoom to commands, it only updates the zoom sesssion on the server. So for moving, the zoom now again uses session "requested_distance" (by the default parameter passed to params.asFloat("distance")). If the user zooms by wheel or pinch, I have to fetch the new zoom value from the server occurs to me just now to reflect it in the new web ui zoom slider. I add this after the issue here is solved.

Still zooming out. I have to check my code.

**Comment by albar965** [comment]
> Same here: I can only test the Win10 build and only when provided some test instructions :)

Sorry. Have no test plan. :slightly_smiling_face:  Anybody?

Having automated GUI tests (can be done with Qt) would be even better.

**Comment by KOKAProduktion** [comment]
Ah sorry, maybe I got it wrong, @u-an-i, you wanted me to test this commit or to help with building?

Cheers

**Comment by u-an-i** [comment]
considered you as help for testing :) but i am almost ready to test myself.

**Comment by u-an-i** [comment]
> (as all commands now obey the same zoom level - the zoom level from the session - and mouse wheel and pinch set the session value - i just thought we can delete the zoom slider from the new ui (thus not needing the new path and not needing to update the slider from one))

once the zoom issue is fixed, @albar965 what do you think of above?

after the zoom fix we would have zoom set by slider and used for everything like "follow aircraft", "show waypoints", "now", ... and user mouse wheel and pinch can override slider (which is why i would want to add a path to sync slider value to corrected distance from server after user mouse wheel or pinch).

before this ubiquitous zoom support "follow aircraft" zoom was set by slider, "show waypoints" was fixed to fit all waypoints into view, "now" zoom took user mouse wheel and pinch zoom.

here i inquire whether we "better" use user mouse wheel and pinch zoom only as the zoom value for all commands: whatever the user zoomed using wheel and pinch is what is used for all commands, no slider necessary anymore and thus i would delete slider from new web ui.

**Comment by albar965** [comment]
Sorry, for late. Trying to catch up ... don't kill me.

About the zoom issue: As far as I remember I kept the current zoom distance in the session store and always passed it to the server. The problem is that I have to zoom out one step on the server to avoid fuzzy maps. Zoom a tiny bit to close and the map is fuzzy. So, its my code which steps out but if you don't do that it will be fuzzy.

You can experience the fuzzyness by zooming with `Shift+Wheel`.

Hope this helps.

**Comment by albar965** [comment]
> here i inquire whether we "better" use user mouse wheel and pinch zoom only as the zoom value for all commands: whatever the user zoomed using wheel and pinch is what is used for all commands, no slider necessary anymore and thus i would delete slider from new web ui.

Feel free to remove it. No need for it if wheel and pinch gestures work.

**Pull request merged**
