### PR TITLE
make look of web ui more consistent with regards to plugin interface

### PR DESCRIPTION
**Pull request by u-an-i**
I detected some optimisation potential of the look of the "Plugins" button and its menu while working on the "autozoom" plugin.
With this PR I implement these improvements as well as utilise the space of the toolbar with regards to button width more efficient to keep the toolbar as small as sensible as long as possible on "mobile devices".

### CODE REVIEW

**Comment by u-an-i** [comment]
@KOKAProduktion would you review this PR ? It has no JS change but only CSS changes and a tiny bit of HTML and thus is a "web PR".

**Comment by u-an-i** [comment]
fine by me. consider reviewing https://github.com/albar965/littlenavmap/pull/775 too

**Comment by KOKAProduktion** [comment]
Aight! My bad then, I have to test it with the recent `master` first. Plz give me a few more hours :)

**Comment by KOKAProduktion** [comment]
Yep! Everything's fine on https://github.com/albar965/littlenavmap/pull/777/commits/4a437eedfe5846cdfe9b65ff3e60193bf501470e

Forget about my previous review. I confirm/approve the changes.

Screenshot (262)

Thanks and cheers!

**Comment by u-an-i** [comment]
Hi, @albar965 this PR can be merged at your convenience.

**Pull request merged**
