### PR TITLE
Feature/web UI alternative

### PR DESCRIPTION
**Pull request by u-an-i**
this PR encompasses offering the possibility to switch to and from an alternative web UI including styling and functionality of that as well as unintrusive inner content adjustment, restoring of inner content selections, overhauled alternative map ui, device standby prevention option.

Thank you for your warm reception of my last PR.

### CODE REVIEW

**Comment by albar965** [comment]
Terrific. I think we can make the "alternative" the default UI. Feel free to send a pull request where this is default. I think you can also ignore my comment on your last PR.

Would it be possible to add a "follows user aircraft" mode to the map? A mode which keeps the user aircraft centered on refresh. Some users requested this recently.
Is mousewheel zoom or two finger pinch zooming doable?
Also: Maybe you can help with #581?

Let me know what you think.

**Comment by u-an-i** [comment]
Thank you for your enthusiasm! I appreciate it! :)

I start switching the alternative and the current making the current "legacy" and the alternative the default.

"Follows user aircraft": I remember the aircraft being part of the map image sent by the server. But the main challenge is to send the LatLng coordinates to the server to tell him to generate the image around those coordinates as center. I didn't see this but I look again. If we solve this "center" parameter (which also needs the zoom level to determine the boundaries), a more elaborate zoom (where mouse pointer is pointing to) for example can be begun and if the aircraft is a separate element it can be tracked in JS as well.
Scroll wheel zoom is possible as is pinch and zoom but will be limited to the existing center (map command "in" to server) until the new center can be relayed to the server.

I feel "helpy" :) , I looked at #581 : I try to do the first point as next feature branch, extracting the ICAO from the flight plan and offering direct lookup. For the second point, again, the server needs to understand a "center=...(&zoom=...)" command.

**Comment by albar965** [comment]
About #581: Feel free to look at this but I'd rather put this into a release after 2.6.12 (beta maybe, in around two weeks or so). I suppose #581 this is a bit of work. I'll leave that up to you.

> Scroll wheel zoom is possible as is pinch and zoom but will be limited to the existing center (map command "in" to server) until the new center can be relayed to the server.

Good enough, IMO for the next update. We can make fancier later, if you're interested. I can add additional server commands, if needed.

> "Follows user aircraft": I remember the aircraft being part of the map image sent by the server. But the main challenge is to send the LatLng coordinates to the server to tell him to generate the image around those coordinates as center. I didn't see this but I look again. 

No need to fiddle with coordinates. There is a command to center the user aircraft:

`http://YOURCOMPUTER:8965/mapimage?format=jpg&quality=100&width=768&height=768&user&distance=1000`

BTW: Did you run into the test page already? `http://YOURCOMPUTER:8965/test.html`

Alex (about 20 NM NW of EDDF)

**Comment by u-an-i** [comment]
> > Scroll wheel zoom is possible as is pinch and zoom but will be limited to the existing center (map command "in" to server) until the new center can be relayed to the server.
> 
> Good enough, IMO for the next update. We can make fancier later, if you're interested. I can add additional server commands, if needed.

I'll prepare it right away and add it after you merge the switch of alternative and original ui!

> No need to fiddle with coordinates. There is a command to center the user aircraft:

right! I'll attempt to make use of it!

> BTW: Did you run into the test page already? `http://YOURCOMPUTER:8965/test.html`
> 
> Alex (about 20 NM NW of EDDF)

Not yet, just looked, thank you ! :)

Lars, S of EDDM

**Comment by 1l2p-dev** [comment]
Hello,

I really enjoy your work, guys. It is really interesting to add these functions to the LNM internal web server.

Few days ago, I just tweaked a little the HTML/JS files to have them working in a MSFS Toolbar in-game Panel. The main goal was to have it in VR mode. I also found useful to add a virtual keyboard that pops out when text fields or areas get the focus. I had to check some CSS (I'm not an expert) to fit in the VR Panel and to modify very few HTML lines. I also put an async double buffering refresh to the LNM moving map display to avoid "flickering" and grey flashes (using "await new" calls and "visibility" attributes of the map images). Then I integrated this tiny virtual JS keyboard ( http://www.greywyvern.com/code/javascript/keyboard ) to search for airport ICAO codes in LNM database and be able to take notes on a text form. As I'm not a truly web developer I can't go further. It was just a rough draft but it works pretty well in the VR cockpit.

I do not know what you think about that, but it might be interesting to add natively this kind of in-game panel feature.

Thanks again,

Philippe.

lnm_panel01

lnm_panel02

**Comment by u-an-i** [comment]
appears intriguing, @1l2p-dev . This opens the door or even requires thinking about a possible plugin approach or similar to accomodate all options on the toolbar.

@albar965 I completed mousewheel zoom and pinch gesture zoom. Works nice! I can add it to the feature/switch-alternative-web-ui-and-original-around branch if you agree.

**Comment by u-an-i** [comment]
> Would it be possible to add a "follows user aircraft" mode to the map? A mode which keeps the user aircraft centered on refresh. Some users requested this recently.

Added in PR https://github.com/albar965/littlenavmap/pull/654

i hope i understood the feature as intended

**Pull request merged**
